--게시글 목록 조회
SELECT * FROM NOTICES  ORDER BY  REGDATE DESC;

SELECT * FROM MEMBERS;

--게시글 조회

SELECT * FROM NOTICES  WHERE CODE="134";

--현재 공지사항에서 가장 큰 코드 얻기

SELECT MAX(TO_NUMBER(CODE)) FROM NOTICES;

SELECT NVL(MAX(TO_NUMBER(CODE)),0)+1 CODE FROM NOTICES;

--20개씩 나눈 레코드를 얻어오는 쿼리를 작성하시오

SELECT * FROM (SELECT * FROM NOTICES ORDER BY REGDATE DESC) 
WHERE ROWNUM BETWEEN 11 AND 20 ;

SELECT * FROM (SELECT ROWNUM NUM , N.* FROM
(SELECT * FROM NOTICES ORDER BY REGDATE DESC) N) 
WHERE NUM BETWEEN 11 AND 20;

SELECT * FROM (SELECT ROWNUM NUM, N.* FROM (SELECT * FROM NOTICES WHERE   like ? ORDER BY REGDATE DESC) N) WHERE NUM BETWEEN 1 AND 3;

INSERT INTO NOTICES(CODE, TITLE, WRITER,CONTENT,REGDATE,HIT) 
VALUES ('160','노력','KJP','야근',SYSDATE,'0');

SELECT COUNT(*) FROM NOTICES; 

--sql 시퀄문 로우넘버 먼저 얻기
SELECT N.* FROM
(SELECT (ROW_NUMBER() OVER (ORDER BY REGDATE DESC)) NUM , NOTICES.* 
FROM NOTICES) N
WHERE N.NUM BETWEEN 11 AND 20;

SELECT CAST(CODE  AS  INT)+1 FROM NOTICEFILES;

--시퀄 서버에서 가장 큰 코드 값을 얻어오기

SELECT ISNULL(MAX(CAST(CODE AS INT)),0)+1 CODE FROM NOTICES;

SELECT (MAX(CAST(CODE AS INT))+1 CODE FROM NOTICEFILES;

SELECT ISNULL(MAX(CAST(CODE AS INT)),0)+1 CODE FROM NOTICEFILES;

SELECT * FROM NOTICEFILES;

SELECT TOP 1 * FROM NOTICES WHERE REGDATE > (SELECT REGDATE FROM NOTICES WHERE CODE = '242') ORDER BY REGDATE ASC;

SELECT TOP 1 * FROM NOTICES WHERE REGDATE < (SELECT REGDATE FROM NOTICES WHERE CODE = '242') ORDER BY REGDATE DESC;
